image: Visual Studio 2019


install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver
  - ps: build\UpdateVersion.ps1

build:
  project: Windows\MassiveKnob.sln

platform:
  - Any CPU

configuration:
  - Release

after_build:
  - cmd: "\"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe\" \"Windows\\Setup\\MassiveKnobSetup.iss\""

deploy:
  provider: GitHub
  auth_token:
    secure: fPvma5Dn9PV65Juan1Lx9AcxoGwLSRIxSjYZGZ46EvI8QoXEUGH0T0fnJDYF5vbM
  artifact: /Windows\\Release\\MassiveKnobSetup-.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true