[package]
name = "readinputs"
version = "0.1.0"
edition = "2021"

[dependencies]
colog = "1.3.0"
crossbeam-channel = "0.5.14"
mk-core = { path = "../../crates/mk-core" }
mk-device-serialmin = { path = "../../crates/mk-device-serialmin" }
mk-actions-pulseaudio = { path = "../../crates/mk-actions-pulseaudio" }
tokio = { version = "1.44.1", features = ["full"] }

[dependencies.log]
version = "0.4.26"
features = ["kv"]

[lints]
workspace = true
