//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassiveKnob.Plugin.VoiceMeeter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassiveKnob.Plugin.VoiceMeeter.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns the output on if the specified parameter equals the specified value..
        /// </summary>
        public static string GetParameterDescription {
            get {
                return ResourceManager.GetString("GetParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceMeeter: Get parameter.
        /// </summary>
        public static string GetParameterName {
            get {
                return ResourceManager.GetString("GetParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides actions to run VoiceMeeter macros or check the current state..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceMeeter Remote.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs a VoiceMeeter macro when the input turns on..
        /// </summary>
        public static string RunMacroDescription {
            get {
                return ResourceManager.GetString("RunMacroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceMeeter: Run macro.
        /// </summary>
        public static string RunMacroName {
            get {
                return ResourceManager.GetString("RunMacroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverted (on if the parameter does not equal the value).
        /// </summary>
        public static string SettingGetParameterInverted {
            get {
                return ResourceManager.GetString("SettingGetParameterInverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name.
        /// </summary>
        public static string SettingGetParameterParameter {
            get {
                return ResourceManager.GetString("SettingGetParameterParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected value.
        /// </summary>
        public static string SettingGetParameterValue {
            get {
                return ResourceManager.GetString("SettingGetParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string SettingRunMacroScript {
            get {
                return ResourceManager.GetString("SettingRunMacroScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: Strip[0].A1 = 1; Strip[0].A2 = 0;
        ///Use comma or semicolons to separate commands, or put each command on a separate line. For more information see the VoiceMeeter documentation on Macro Buttons..
        /// </summary>
        public static string SettingRunMacroScriptExample {
            get {
                return ResourceManager.GetString("SettingRunMacroScriptExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoiceMeeter version.
        /// </summary>
        public static string SettingVoiceMeeterVersion {
            get {
                return ResourceManager.GetString("SettingVoiceMeeterVersion", resourceCulture);
            }
        }
    }
}
