[package]
name = "massiveknob_backend"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.86"
log = "0.4.21"
platform-dirs = "0.3.0"
regex = "1.10.5"
rust-i18n = "3.0.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serialport = { version = "4.4.0", default-features = false }
tracker = "0.2.2"

[dependencies.uuid]
version = "1.10.0"
features = [ "v4", "fast-rng", "macro-diagnostics" ]

[dependencies.min-rs]
git = "https://github.com/MvRens/min-rs.git"
