//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassiveKnob {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassiveKnob.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not configured.
        /// </summary>
        public static string ActionNotConfigured {
            get {
                return ResourceManager.GetString("ActionNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string DeviceStatusConnected {
            get {
                return ResourceManager.GetString("DeviceStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string DeviceStatusConnecting {
            get {
                return ResourceManager.GetString("DeviceStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string DeviceStatusDisconnected {
            get {
                return ResourceManager.GetString("DeviceStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are assigning a digital action to an analog output. Please specify how you want to represent the on and off values..
        /// </summary>
        public static string DigitalToAnalogDescription {
            get {
                return ResourceManager.GetString("DigitalToAnalogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string DigitalToAnalogOff {
            get {
                return ResourceManager.GetString("DigitalToAnalogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string DigitalToAnalogOn {
            get {
                return ResourceManager.GetString("DigitalToAnalogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input #{0}.
        /// </summary>
        public static string InputHeader {
            get {
                return ResourceManager.GetString("InputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string LoggingEnabled {
            get {
                return ResourceManager.GetString("LoggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging level.
        /// </summary>
        public static string LoggingLevel {
            get {
                return ResourceManager.GetString("LoggingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LoggingLevelError {
            get {
                return ResourceManager.GetString("LoggingLevelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only serious errors are logged..
        /// </summary>
        public static string LoggingLevelErrorDescription {
            get {
                return ResourceManager.GetString("LoggingLevelErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string LoggingLevelInformation {
            get {
                return ResourceManager.GetString("LoggingLevelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information, warnings and errors are logged. This is the recommended level..
        /// </summary>
        public static string LoggingLevelInformationDescription {
            get {
                return ResourceManager.GetString("LoggingLevelInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose.
        /// </summary>
        public static string LoggingLevelVerbose {
            get {
                return ResourceManager.GetString("LoggingLevelVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like big logs and I can not lie!.
        /// </summary>
        public static string LoggingLevelVerboseDescription {
            get {
                return ResourceManager.GetString("LoggingLevelVerboseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LoggingLevelWarning {
            get {
                return ResourceManager.GetString("LoggingLevelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings and errors are logged. This includes issues with loading plugins..
        /// </summary>
        public static string LoggingLevelWarningDescription {
            get {
                return ResourceManager.GetString("LoggingLevelWarningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs are saved to {0}.
        /// </summary>
        public static string LoggingOutputPath {
            get {
                return ResourceManager.GetString("LoggingOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string MenuGroupDevice {
            get {
                return ResourceManager.GetString("MenuGroupDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuGroupSettings {
            get {
                return ResourceManager.GetString("MenuGroupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog inputs.
        /// </summary>
        public static string MenuItemAnalogInputs {
            get {
                return ResourceManager.GetString("MenuItemAnalogInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog outputs.
        /// </summary>
        public static string MenuItemAnalogOutputs {
            get {
                return ResourceManager.GetString("MenuItemAnalogOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string MenuItemDevice {
            get {
                return ResourceManager.GetString("MenuItemDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital inputs.
        /// </summary>
        public static string MenuItemDigitalInputs {
            get {
                return ResourceManager.GetString("MenuItemDigitalInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital outputs.
        /// </summary>
        public static string MenuItemDigitalOutputs {
            get {
                return ResourceManager.GetString("MenuItemDigitalOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string MenuItemLogging {
            get {
                return ResourceManager.GetString("MenuItemLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string MenuItemPlugins {
            get {
                return ResourceManager.GetString("MenuItemPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string MenuItemStartup {
            get {
                return ResourceManager.GetString("MenuItemStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output #{0}.
        /// </summary>
        public static string OutputHeader {
            get {
                return ResourceManager.GetString("OutputHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run MassiveKnob at startup.
        /// </summary>
        public static string RunAtStartup {
            get {
                return ResourceManager.GetString("RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massive Knob - Settings.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
    }
}
